# Generated by Django 5.2.1 on 2025-06-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kategoria', models.CharField(choices=[('elektronika', 'Elektronika'), ('gry', 'Gry'), ('ubrania', 'Ubrania')], max_length=20)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
