# Generated by Django 5.2.1 on 2025-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elektrosklep', '0002_koszyk_pozycjakoszyka_zamowienie_pozycjazamowienia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='produkty/'),
        ),
    ]
